In [2]:
import numpy as np
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import LSTM, Dense

In [3]:
X = []
Y = []
for i in range(5, 20):
    X.append([[j] for j in range(i - 5, i)])
    Y.append([i])

In [4]:
X = np.array(X)
Y = np.array(Y)

In [5]:
print(X.shape)
print(Y.shape)
print(X)
print(Y)

(15, 5, 1)
(15, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[ 8]
  [ 9]
  [10]
  [11]
  [12]]

 [[ 9]
  [10]
  [11]
  [12]
  [13]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[12]
  [13]
  [14]
  [15]
  [16]]

 [[13]
  [14]
  [15]
  [16]
  [17]]

 [[14]
  [15]
  [16]
  [17]
  [18]]]
[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [6]:
# LSTM 모델 구성
# LSTM 레이어 50개층, Dense 레이어 1개층으로 구성된 모델
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(5, 1)))
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [7]:
# 모델 학습
hist = model.fit(X, Y, epochs=100, batch_size=1)

Epoch 1/100
15/15 [==============================] - 9s 12ms/step - loss: 225.4803 - accuracy: 0.0000e+00
Epoch 2/100
15/15 [==============================] - 0s 9ms/step - loss: 159.8356 - accuracy: 0.0000e+00
Epoch 3/100
15/15 [==============================] - 0s 9ms/step - loss: 51.7767 - accuracy: 0.0000e+00
Epoch 4/100
15/15 [==============================] - 0s 9ms/step - loss: 18.5908 - accuracy: 0.0000e+00
Epoch 5/100
15/15 [==============================] - 0s 9ms/step - loss: 8.2704 - accuracy: 0.0000e+00
Epoch 6/100
15/15 [==============================] - 0s 9ms/step - loss: 5.6170 - accuracy: 0.0000e+00
Epoch 7/100
15/15 [==============================] - 0s 9ms/step - loss: 4.1614 - accuracy: 0.0000e+00
Epoch 8/100
15/15 [==============================] - 0s 8ms/step - loss: 3.1582 - accuracy: 0.0000e+00
Epoch 9/100
15/15 [==============================] - 0s 8ms/step - loss: 2.5394 - accuracy: 0.0000e+00
Epoch 10/100
15/15 [==============================] - 0s 10ms/step

In [8]:
import matplotlib.pyplot as plt
plt.title('Loss')
plt.plot(hist.history['loss'])
plt.xlabel('epoch')
plt.ylabel('loss')
plt.show()

In [9]:
# 다음 값을 예측
next_value = np.array([[[16], [17], [18], [19], [20]]])
# next_value = np.array([[[1], [2], [3], [4], [5]]])
predicted_value = model.predict(next_value)
# print(f"predict value: {predicted_value[0][0]}")
print(f"predict value: {predicted_value[0][0]}")

predict value: 20.41552734375
